### ISSUE TITLE
Metadata format for the LANDRegistry

### ISSUE THREAD

**Issue by abarmat** [decentraland/marketplace#10]
* Evaluate alternatives for the string metadata for each parcel of LAND (csv, json vs others).
* Should have some form of versioning if we decided to upgrade in the future.
* Should take into account that storing data in Ethereum has high costs and we should keep it minimal.
* Provide a clear definition of the format so third-parties can use.

**Comment by ferittuncer** [comment]
I was just checking the issues and stumbled upon this. Have you considered YAML? Would it be much more readible at a cost of few spaces?

**Comment by abarmat** [comment]
@ferittuncer it is more readable but we are optimizing for storage which turns into more cost for every transaction in Ethereum. CSV is easy to parse, we can upgrade with the version number and it's quite readable.

**Comment by abarmat** [comment]
I'm closing this issue as it's already settled. We can open a new issue for upgrades.
