### ISSUE TITLE
Name and description pending status not cleared

### ISSUE THREAD

**Issue by dafky2000** [decentraland/marketplace#126]
The name and description were changed, tx has been confirmed, have had other successful tx since then. EthAlarm issues?

![screenshot_2018-03-19_15-12-53](https://user-images.githubusercontent.com/2653187/37616979-04a478c8-2b88-11e8-8171-e68bd1f11e66.png)

**Comment by cazala** [comment]
This was due to a bug that was causing transactions to get stuck on pending status on the UI. It has been fixed by #128.
