### ISSUE TITLE
Update the Sign in modal in Mobile

### ISSUE THREAD

**Issue by nicorajcodcl** [decentraland/marketplace#1413]
## 🎉 Description

Currently, this is how the Mobile modal looks:

![image.png](https://images.zenhubusercontent.com/63074b6c3d1e525cad8f134a/3545a249-a4b5-49cb-9c12-39b6a99f7a99)

It doesn't show the MetaMask option at first sight (it's hidden after WalletConnect). 

The desktop modal works better as it shows the most used log-in option (MM) as the first alternative and clearly visible. We should do the same in mobile so the modal displays the MM option first and visible outside wallet connect. 

![image.png](https://images.zenhubusercontent.com/63074b6c3d1e525cad8f134a/fb077b40-2ab5-4fc4-8648-fab1d9210255)

In this case, we should add the MM option in the mobile modal, but with a change of copy. Instead of putting "Using a browser extension" (as in desktop), replace it with "Using the MetaMask app"

Also, try to make it fit better on the screen (the screenshot are taken from an iPhone 12 mini)

* [ ] 🐛 This is a bug report.
* [X] 📈 This is a feature request.

## 📝 Details

Describe the problem you have been experiencing in more detail. Include as much information as you think is relevant. Keep in mind that transactions can fail for many reasons; context is key here. Links to tx, screenshots are welcome.
Remember to not share sensible information

## 🔢 Steps To Reproduce Issue [ Good To Have ]

Please remember that with baby steps it's easier to reproduce the bug and it's much faster to fix it.

```
- Step 1
- Step 2
- Step 3
...
```

**Comment by LautaroPetaccio** [comment]
Closing it as the log in site has changed to auth.
