### ISSUE TITLE
[2.2] Add new status filter and persist the filter in the URL

### ISSUE THREAD

**Issue by flobarreto** [decentraland/marketplace#1433]
https://www.notion.so/decentraland/Unified-Markets-65195514608c429fbba4e0d0884fde3c?pvs=4#0607185f58984d879c759477ef7d9694
Create ui filter and apply the status to the URL parameters so it gets to the new endpoint of listings as the sortBy condition.

![image.png](https://images.zenhubusercontent.com/6361163a05a9f23cf519aa74/3681def9-dd91-4cb0-94da-abe37cd38e2f)

**Comment by LautaroPetaccio** [comment]
Closing it as it's already done.
