### ISSUE TITLE
[2.3] Remove the assetType filter and the top bar component that toggles between primary and secondary markets

### ISSUE THREAD

**Issue by flobarreto** [decentraland/marketplace#1434]
This component won’t be needed once we have all unified. Let’s leave this one to the end, once we have the cards already unified and the concepts of assetType is deprecated

![image.png](https://images.zenhubusercontent.com/6361163a05a9f23cf519aa74/7d7a8cad-9391-4042-bbd2-1039302c46cb)

**Comment by LautaroPetaccio** [comment]
Closing it as it's already done.
