### ISSUE TITLE
[3.3] Create the new listings table. Including sort and pagination

### ISSUE THREAD

**Issue by flobarreto** [decentraland/marketplace#1437]
This component is basically a component that fetches the `/orders` endpoint that we currently have. It needs to look for those orders with `status` `open` and not expired. All the data rendered here is provided by the endpoint. The table needs to support sorting and pagination. `sortBy` right now supports `recently_listed, recently_updated, cheapest`, we would need to add by `tokenId` (for issue number).

Listings can be sorted by:

- Cheapest (default)
- Newest
- Oldest
- Issue number ⬇️
- Issue number ⬆️

Notes: 

- [use decentraland-ui table](https://ui.decentraland.org/?path=/story/table--polls)
- **Each row redirects to the corresponding NFT page.**

![image.png](https://images.zenhubusercontent.com/6361163a05a9f23cf519aa74/5b41deaa-0842-4451-8984-92539cc5ba53)

**Comment by LautaroPetaccio** [comment]
Closing it as it's already done.
