### ISSUE TITLE
[4.1] Re-order the nft basic info into the new component. 

### ISSUE THREAD

**Issue by flobarreto** [decentraland/marketplace#1439]
It should re-use the componentes used for the item. Let’s create those components in a way it renders the fields coming from both item/nft. 

![image.png](https://images.zenhubusercontent.com/6361163a05a9f23cf519aa74/8e9397ad-4135-4494-803d-b8a73af9fcfd)

**Comment by LautaroPetaccio** [comment]
Closing it as it's already done.
