### ISSUE TITLE
[4.4] Add the “Other offers” section

### ISSUE THREAD

**Issue by flobarreto** [decentraland/marketplace#1442]
This section will list other bids. Use the /bids endpoints that we currently have, it should return all the data needed for the table. It should be paginated and be sortable.

![image.png](https://images.zenhubusercontent.com/6361163a05a9f23cf519aa74/ce72340e-39c1-43f9-9c10-cc9a66c68c55)

**Comment by LautaroPetaccio** [comment]
Closing it as it's already done.
