### ISSUE TITLE
Add pre-commit to the marketplace

### ISSUE THREAD

**Issue by cyaiox** [decentraland/marketplace#1445]
Add pre-commit to the marketplace using Husky.

This pre-commit script should validate eslint rules and apply prettier defined styles included in [eslint-config-dapps](https://github.com/decentraland/eslint-config-dapps).

Tasks:
- [ ] Fix all invalid eslint rules
- [ ] Fix prettier invalid styles
- [x] Add husky dependency
- [x] Add husky pre-commit script

**Comment by LautaroPetaccio** [comment]
Closing it as it's already done.
