### ISSUE TITLE
Dropdown items width

### ISSUE THREAD

**Issue by flobarreto** [decentraland/marketplace#1448]
Dropdown items on rent period for land are bigger than the dropdown. Make them the same width.

![image.png](https://images.zenhubusercontent.com/6361163a05a9f23cf519aa74/0b527101-4978-4712-90d5-31ebcd245410)

**Comment by shamim-io** [comment]
@flobarreto can you please assign this issue to me?

**Comment by Karribalu** [comment]
I don't see this issue in the UI now, I think it can be closed now
<img width="380" alt="Screenshot 2023-05-24 at 00 21 50" src="https://github.com/decentraland/marketplace/assets/42462452/299950d9-0664-4392-a676-79af4e9f5f65">

**Comment by LautaroPetaccio** [comment]
Closing it as it's already done.
