### ISSUE TITLE
Create the new "My Lists" page and tab

### ISSUE THREAD

**Issue by kevinszuchet** [decentraland/marketplace#1482]
1. There should be a new tab in the Navigation header called "My Lists"
2. It should redirect to the "My Lists" page
3. It should query the `favorites-server` in order to get all the favorited items ids for the connected user
 3.1 Check if it's possible to use a skeleton loader until the `nft-server` responds
4. With that favorited items ids for the connected users, it should query the `nft-server` to get the items data
5. Display those items using the Asset Card component
6. Paginate the page (infinite scrolling could be an option)
7. Add a link to the new tab in the profile menu

![image.png](https://images.zenhubusercontent.com/636115f91bf3a9253642c51e/f54abbdb-57c7-4916-ab32-4a375f618b95)

On `unpick` show a modal with a confirmation message and a checkbox to never show that modal again.

![image.png](https://images.zenhubusercontent.com/636115f91bf3a9253642c51e/a143a2e3-fc24-487c-8e15-7efbdb126bba)

**Comment by kevinszuchet** [comment]
Hi @Chakravarthy7102, we appreciate your willingness to collaborate.

Even though your help would be more than welcome, the feature is not ready yet to be implemented because it still needs some setup.

We have some other `good-first-issues` with a high impact:
- https://github.com/decentraland/builder/issues/1011
- https://github.com/decentraland/marketplace/issues/699

Do you want to take them?

**Comment by Chakravarthy7102** [comment]
@kevinszuchet  Yeah Sure!, but once the setup is finished, please tag me okay?
