### ISSUE TITLE
[3.8] redesign of tables to match new figma designs

### ISSUE THREAD

**Issue by flobarreto** [decentraland/marketplace#1511]
[Figma link here](https://www.figma.com/file/6Pc7qk51jkAuwgaFNSfJLe/Unified-Markets?node-id=890-137979&t=E9DwQNdgRUu21bDO-0)

### New styles: 
![image.png](https://images.zenhubusercontent.com/6361163a05a9f23cf519aa74/45a8294e-a1e5-4ded-b027-bd162200d861)

### Tables to modify:
**listings** 
![image.png](https://images.zenhubusercontent.com/6361163a05a9f23cf519aa74/16f20a60-9d9b-4512-ad61-87fae434d9de)

**owners **
![image.png](https://images.zenhubusercontent.com/6361163a05a9f23cf519aa74/76f1c4d8-95eb-4178-9b57-ca8185628b0e)

**transaction history** 
![image.png](https://images.zenhubusercontent.com/6361163a05a9f23cf519aa74/e2fcb460-7973-42b7-9796-0e186c59d00d)

**rental history** 
![image.png](https://images.zenhubusercontent.com/6361163a05a9f23cf519aa74/36f1d039-b110-4726-97ef-56e1fcb94317)

**collection page** 
![image.png](https://images.zenhubusercontent.com/6361163a05a9f23cf519aa74/60d1cea5-34d9-413d-986c-1a2e365c11b5)

**onsale or rent list**
![image.png](https://images.zenhubusercontent.com/6361163a05a9f23cf519aa74/acef5256-d714-411c-8161-1ef86598912e)

**rankings**
![image.png](https://images.zenhubusercontent.com/6361163a05a9f23cf519aa74/442a9605-b1d9-47ac-8a80-764d2728d11e)

**recently sold**
![image.png](https://images.zenhubusercontent.com/6361163a05a9f23cf519aa74/59a65477-9364-4f36-aa1d-22a4b7ccc9b2)

**Comment by LautaroPetaccio** [comment]
Closing it as it's already done.
