### ISSUE TITLE
Most expensive toggle has method name in it.

### ISSUE THREAD

**Issue by ev0lv3vr** [decentraland/marketplace#156]
![screen shot 2018-03-22 at 1 26 28 pm](https://user-images.githubusercontent.com/1928987/37796523-c0f1962a-2dd4-11e8-85d0-ed5d54fe2cde.png)

Incorrect name for the filter as per the screenshot.

**Comment by abarmat** [comment]
Could you please refresh the screen? It seems your UI is using an old version of the dictionary.

You can do cmd+shift+R

**Comment by ev0lv3vr** [comment]
refreshed, now we are missing "most expensive"

![screen shot 2018-03-22 at 1 34 24 pm](https://user-images.githubusercontent.com/1928987/37796945-b5e47f4e-2dd5-11e8-958c-c63f9a376c95.png)

**Comment by ev0lv3vr** [comment]
suggesting to update integration suite for filters in general.

**Comment by cazala** [comment]
It has been removed by #147 because users abused it

**Comment by cazala** [comment]
We are planning on introducing better filtering options (like min/max price for example) instead of keeping this type of sorting that can be easily abused.

**Comment by ev0lv3vr** [comment]
ok closing this one
