### ISSUE TITLE
IOs atlas zoomOut does not work after certain value

### ISSUE THREAD

**Issue by ev0lv3vr** [decentraland/marketplace#157]
Attaching screenshot with atlas being zoomed out at max on ios/iphone6
![img_0794](https://user-images.githubusercontent.com/1928987/37797302-a629d8b4-2dd6-11e8-8515-03feb9473e79.jpg)

This is preventing users from browsing the map in portrait and landscape view.

**Comment by cazala** [comment]
This' been fixed already
