### ISSUE TITLE
Error connecting Ledger to market on Firefox

### ISSUE THREAD

**Issue by iamkubi** [decentraland/marketplace#158]
Running Firefox 59.0.1 (64-bit) on Windows 10.  When attempting to connect to a Ledger from the sign-in page receive an error in the console, market just redirects back to the login page repeatedly.  Tried on Chrome and I'm able to use the Ledger successfully.  Previously I had been using MetaMask on Firefox successfully.  I disabled MetaMask and restarted Firefox, but still was unable to connect.

Console error:
[Ethereum] Error trying to connect Ethereum wallet: Could not get a valid provider for web3
rollbar.min.js:2:19646
Error trying to connect to Ethereum for the 3th time 
Error: Could not connect to Ethereum
Stack trace:
e/<@https://market.decentraland.org/static/js/main.263ad06c.js:1:359121
r@https://market.decentraland.org/static/js/main.263ad06c.js:1:1560812
c/<@https://market.decentraland.org/static/js/main.263ad06c.js:1:1561860
s/</e[t]@https://market.decentraland.org/static/js/main.263ad06c.js:1:1560988
r@https://market.decentraland.org/static/js/main.263ad06c.js:1:358290
r/<@https://market.decentraland.org/static/js/main.263ad06c.js:1:358388
C/</<@https://market.decentraland.org/static/js/main.263ad06c.js:1:1314804
C/<@https://market.decentraland.org/static/js/main.263ad06c.js:1:1314674
c@https://market.decentraland.org/static/js/main.263ad06c.js:1:366167
rollbar.min.js:2:19646
 action [Failure] Connect Wallet @ 20:40:22.174

**Comment by NicoSantangelo** [comment]
This is a limitation with Firefox, it doesn't fully support U2F AFIK. You might want to try this addon https://addons.mozilla.org/en-US/firefox/addon/u2f-support-add-on/ but we are currently not "officially" testing it.

[More info from the ledger provider we're using](https://www.npmjs.com/package/ledger-wallet-provider#requirements).

I'll close this but feel free to report back (and @ me if you want) if you need help or found more information.
