### ISSUE TITLE
FR: Ability to select an address other than the default on Ledger wallet

### ISSUE THREAD

**Issue by iamkubi** [decentraland/marketplace#159]
After successfully connecting my Ledger to the market it gives me the option to select the derivation path, but it does not allow me to specify an address on the wallet.  It appears to only allow use of the first address, and in my case that is not the address where my MANA or ETH are stored.

It would be nice if I could select a different wallet address rather than have to move coins around.

**Comment by eordano** [comment]
Hi there,

We're aware of this UX issue -- we consider this an expert use case and might take some time to fix this. The address is determined by your derivation path -- so if you know the correct derivation path it should be working. Thanks!

**Comment by sean1000444** [comment]
Is there any way to reconsider this or has there been any movement on this? It really seems like a regular use case for anyone using a Ledger as the addresses that Ledger Live and MEW generate are different from those which the Marketplace comes up with. This makes it quite a hassle to verify that the Marketplace's address is correct and accessible from one's Ledger then transfer ETH; MANA; and LAND to that address just to use the Marketplace.
