### ISSUE TITLE
Update Activity Icon

### ISSUE THREAD

**Issue by nicorajcodcl** [decentraland/marketplace#1607]
## 🎉 Description

Now the Activity icon in the Marketplace is a Bell, which resembles a Notification section in the mind of most users. We should change that icon for the one proposed here (the new icon is a clock with an arrow):
https://www.figma.com/file/6Pc7qk51jkAuwgaFNSfJLe/Unified-Markets?node-id=961-165166&t=NTyOF0spfaoACDup-0

**Important:** Implement this change in the launch of Unified Markets so that all small changes are sent at once and it doesn't seem broken or disconnected. 

* [ ] 🐛 This is a bug report.
* [X] 📈 This is a feature request.

## 📝 Details

Describe the problem you have been experiencing in more detail. Include as much information as you think is relevant. Keep in mind that transactions can fail for many reasons; context is key here. Links to tx, screenshots are welcome.
Remember to not share sensible information

## 🔢 Steps To Reproduce Issue [ Good To Have ]

Please remember that with baby steps it's easier to reproduce the bug and it's much faster to fix it.

```
- Step 1
- Step 2
- Step 3
...
```

**Comment by LautaroPetaccio** [comment]
Closing it as it's already done.
