### ISSUE TITLE
On section section has the loader missplaced

### ISSUE THREAD

**Issue by juanmahidalgo** [decentraland/marketplace#1642]
## 🎉 Description

As the title describes, go to `/account?section=on_sale` and look at the Loader, it's on the right top corner instead of centered. 

* [x] 🐛 This is a bug report.
* [ ] 📈 This is a feature request.

![image.png](https://images.zenhubusercontent.com/61e56f8bfe61d4326945f317/b3d8658c-9921-4e20-9154-d2dbbfd41d85)

**Comment by LautaroPetaccio** [comment]
Closing it as it's already done.
