### ISSUE TITLE
Review and update campaigns doc

### ISSUE THREAD

**Issue by flobarreto** [decentraland/marketplace#1707]
https://www.notion.so/decentraland/Creating-a-Marketplace-Builder-Campaign-fa3b1f340d5d4b85af06399db64a4074

**Comment by flobarreto** [comment]
https://www.notion.so/Creating-a-Marketplace-Builder-Campaign-fa3b1f340d5d4b85af06399db64a4074?d=4ddb14d089dd4af68d784248c62e7e9b#c748ae8002e3493c85ea3f59c54594ed

**Comment by LautaroPetaccio** [comment]
Closing this as it's already done.
