### ISSUE TITLE
Allow users to remove items from multiple lists using the Save to Lists modal

### ISSUE THREAD

**Issue by kevinszuchet** [decentraland/marketplace#1717]
If the user clicks on the bookmark icon of an item that has already been saved in a list, the marketplace should display a modal similar to the Save to Lists modal but with the title "Edit Lists".

![image.png](https://images.zenhubusercontent.com/636115f91bf3a9253642c51e/32529cf2-1b54-488d-97d1-2aab75be271a)

The behavior of the CTAs should be the same as the original Save to Lists modal.

**Comment by LautaroPetaccio** [comment]
Close due to #1716
