### ISSUE TITLE
[Feature Request] The Marketplace: Auction Sell

### ISSUE THREAD

**Issue by ferittuncer** [decentraland/marketplace#182]
Dear Decentraland developers and enthusiasts,

I think it would be great if we could auction our lands. This would be much easier than relisting again and again until we find a reasonable (hopefully best) price for our land.

Auction could work like this:

1. A seller puts a particular parcel to auction with some deadline. 
2. Some buyers bid.
3. When the deadline is reached highest bidder buys.

- A seller also can set a price for immediate sale.
- A seller can set minimum bid increase rate (e.g. minimum increase should be 1.1x)
- A seller can set a rule such as `deadline = max(deadline, now+5hours)`

What do you think?

**Comment by rushughes** [comment]
an auction system would allow the market to accurately determine the price of lands and create more liquidity for the land market and in turn the mana market

**Comment by petey702** [comment]
it will initially lower post prices but, if it's a simple fix and there are no other problems anyone sees with it then i think it may be a fine change. if it's not simple to change, they'd have to weigh out the "benefits"

**Comment by ferittuncer** [comment]
Closing this issue as there is no feedback from maintainers.
