### ISSUE TITLE
Nav-bar disappears in success page after buying with MANA

### ISSUE THREAD

**Issue by nicorajcodcl** [decentraland/marketplace#1907]
## 🎉 Description

If I buy an item with MANA, I see the success page with the confetti confirming that the item is already mine. The Navbar of the marketplace that shows the overview, collectibles, my assets, etc. sections should persist. Now it is disappearing. 

![image.png](https://images.zenhubusercontent.com/63074b6c3d1e525cad8f134a/342e9817-8e38-43e1-b083-86a8bedd6aa2)

* [X] 🐛 This is a bug report.
* [ ] 📈 This is a feature request.

## 📝 Details

Describe the problem you have been experiencing in more detail. Include as much information as you think is relevant. Keep in mind that transactions can fail for many reasons; context is key here. Links to tx, screenshots are welcome.
Remember to not share sensible information

## 🔢 Steps To Reproduce Issue [ Good To Have ]

Please remember that with baby steps it's easier to reproduce the bug and it's much faster to fix it.

```
- Step 1
- Step 2
- Step 3
...
```

**Comment by LautaroPetaccio** [comment]
Using #2221 should resolve the issue.
