### ISSUE TITLE
Indexer module failed to install dependencies.

### ISSUE THREAD

**Issue by yiluoe** [decentraland/marketplace#2020]
<img width="1687" alt="image" src="https://github.com/decentraland/marketplace/assets/144141994/c2b333df-6a0a-4334-bed9-30358835a89c">

**Comment by meelrossi** [comment]
Hi @yiluoe! how are you?

It seems that the repo holding that dependency was deleted. For now, you can try updating the graph-cli dependency in the `package.json` file to a later version. We will try to do the upgrade as soon as possible.

**Comment by yiluoe** [comment]
> 你好@yiluoe！你好吗？
> 
> 似乎持有该依赖项的存储库已被删除。现在，您可以尝试将文件中的 graph-cli 依赖项更新`package.json`到更高版本。我们将尽最大努力进行升级。

OK, thanks!
