### ISSUE TITLE
mf_sammichgamer collection thumbnails not shown

### ISSUE THREAD

**Issue by pabloes** [decentraland/marketplace#244]
The url of the images are pointing to
`https://wearable-api.decentraland.org/v2/collections/meme_dontbuythis/wearables/xxxx`
while it should be
`https://wearable-api.decentraland.org/v2/collections/mf_sammichgamer/wearables/xxxx`

so, mf_sammichgamer collection items has wrong collection id on url

**Comment by nachomazzara** [comment]
Thanks for reporting. The fix is addressed at #245
