### ISSUE TITLE
Ropsten MarketPlace Active?

### ISSUE THREAD

**Issue by isaiahcurry8** [decentraland/marketplace#251]
I am trying to test out a dapp that I am building and I would like to execute purchases of land. Is that possible with the MarketPlace contract on the Ropsten test network? Is there a way for me to transfer a NFT token to a wallet?

**Comment by nachomazzara** [comment]
Hi! This is not an issue of the marketplace repo itself. I strongly recommend you to use support channels as discord or intercom. 

If you want to use the marketplace and LAND contract, you can easily deploy your own contracts in Ropsten by copy/paste the code. All the contracts are public and validated.

Thanks
