### ISSUE TITLE
Where can I change the RPC

### ISSUE THREAD

**Issue by Speedevs** [decentraland/marketplace#266]
How can i change the RPC to another mainnet

**Comment by Speedevs** [comment]
e.g. want to change from ethereum RPC to other RPC in metamask

**Comment by nachomazzara** [comment]
You may need to [add a custom network](https://metamask.zendesk.com/hc/en-us/articles/360043227612-How-to-add-custom-Network-RPC-and-or-Block-Explorer) on Metamask.
