### ISSUE TITLE
Help forking 

### ISSUE THREAD

**Issue by Specbee-onchain** [decentraland/marketplace#272]
Hey, I faced a problem with the INDEXER subgraph, it does not show any entities through the network, and all contracts are correct. Check https://thegraph.com/explorer/subgraph/bear-finance/marketplace and my contracts https://contracts.bears.finance/addresses.json. I created orders manually on ropsten via Marketplace contract directly - it works cool, the UI and subgraph of the marketplace does not give any data. I deployed everything related to marketplace after reading carefully and browsing through Decentraland repositories. 
<img width="1609" alt="Screenshot 2021-04-28" src="https://user-images.githubusercontent.com/82381305/116395844-50f28d80-a82d-11eb-88a7-a4f87c76ca22.png">

.env file of the webapp (UI) 
<img width="1136" alt="Screenshot 2021-04-28" src="https://user-images.githubusercontent.com/82381305/116397117-daef2600-a82e-11eb-9edf-e5f9fc929356.png">

**Comment by Specbee-onchain** [comment]
@eordano @abarmat @2fd @menduz

**Comment by nachomazzara** [comment]
Check the `env` from `./ci/.env.prd`.  `CHAIN_ID` should be 1

**Comment by nachomazzara** [comment]
Contracts addresses are different from the Decentraland Ropsten ones.  You can check them [here](https://contracts.decentraland.org/addresses.json)

**Comment by Specbee-onchain** [comment]
Yeah, I have seen that, the contracts are different since I try to fork out the marketplace for different token and LAND registry.  I wonder perhaps you can provide a paid document on how to setup the marketplace for a new token (new project not decentraland) on ropsten network.

**Comment by Specbee-onchain** [comment]
The repository I am working on https://github.com/BEAR-finance/marketplace (complete fork of the latest version of the Decentraland's NFT marketplace)

**Comment by Specbee-onchain** [comment]
Are you ok with $300 in USDT for a simple step-by-step doc for setting up the marketplace with a new set of contracts? @nachomazzara

**Comment by Specbee-onchain** [comment]
$900?

**Comment by nachomazzara** [comment]
Hey, no thanks. It is not a priority right now. You need to mint your tokens in order to have them indexed in your subgraph

**Comment by nachomazzara** [comment]
Closing this in favor of https://github.com/decentraland/land/issues/153
