### ISSUE TITLE
Error Deploying to Graph Node

### ISSUE THREAD

**Issue by jp185357** [decentraland/marketplace#273]
Trying to get the Indexer to build locally. Have IPFS up and running. Not running into any compile errors but it just sits at `Deploying to Graph node http://127.0.0.1:8020` indefinitely.

Any tips / tricks ti progress from here?

![image](https://user-images.githubusercontent.com/54908567/116446582-1684f280-a825-11eb-9b36-bad9112332ab.png)

Also running into an issue getting the webapp running locally. Getting the error:

![image](https://user-images.githubusercontent.com/54908567/116446960-7aa7b680-a825-11eb-9387-1a630a68f515.png)

**Comment by nachomazzara** [comment]
Do you have a `graph-node` running on localhost at that port? Maybe you can refer to this [link](https://github.com/graphprotocol/graph-node) to run your own graph-node

**Comment by bn185068** [comment]
@nachomazzara thanks for the response! I actually did follow that link to get a graph-node running, but it only seemed to run on mainnet. I couldn't figure out how to get it to run on ropsten.

**Comment by nachomazzara** [comment]
At 
```
cargo run -p graph-node --release -- \
  --postgres-url postgresql://USERNAME[:PASSWORD]@localhost:5432/graph-node \
  --ethereum-rpc [URL] \
  --ipfs 127.0.0.1:5001
  ```
  
`--ethereum-rpc [URL]` _URL_ is the RPC endpoint you need. 

It is recommended to have a local Ethereum node with the HTTP RPC available to do it. Services as Infura or alchemy will rate limit you for querying too much. Also archive data is a paid service.

**Comment by jp185357** [comment]
Thanks for the reply, @nachomazzara

> Do you have a `graph-node` running on localhost at that port? Maybe you can refer to this [link](https://github.com/graphprotocol/graph-node) to run your own graph-node.
> 
Did not but am seeing the direction this is going.. Will look into the local ETH node. thank you

> Related to the compile error, which node version are you using? try using node 12 or 14
>
Running on node v14.15.4

**Comment by jp185357** [comment]
@nachomazzara

got a local ethereum node setup on ropsten using geth
got the graph-node setup and connected to the local http rpc

Still getting this error though when trying to deploy the graph node locally..
```
Failed to deploy to Graph node http://127.0.0.1:8020/: Ethereum network not supported by registrar: ropsten
```

& I can see this attempt to deploy to the graph-node but am getting this error message
```
graph-node_1  | Apr 29 01:51:35.077 ERRO subgraph_deploy failed, params: SubgraphDeployParams { name: SubgraphName("decentraland/marketplace"), ipfs_hash: DeploymentHash("QmYRaG4Z1mQtVq1VuF7koNDFtQJi34eENoVpEnpKmo5nrR"), node_id: None }, error: NetworkNotSupported("ropsten"), component: JsonRpcServer
```

does this happen to mean anything to you?

**Comment by jp185357** [comment]
Actually I just noticed this additional log error...
```
ERRO Not starting block ingestor (chain is defective), network_name: ropsten
```

I have a feeling this means that something is out of sync with the chain or something..

**Comment by nachomazzara** [comment]
I've never seen that issue before. Have you contacted thegraph team?

**Comment by jp185357** [comment]
Have not - Will try them now. Thanks!

**Comment by nachomazzara** [comment]
Let me know so we can close the issue
