### ISSUE TITLE
NFT products are not displayed

### ISSUE THREAD

**Issue by mobin-ux** [decentraland/marketplace#294]
Hello
I used the marketplace before and the posts were displayed well on the main page
But for several days now, the posts have not been displayed!

![image](https://user-images.githubusercontent.com/71329439/118865125-e5648300-b8f5-11eb-85d5-0cc7e0b8ecd9.png)

**Comment by mobin-ux** [comment]
root@blockartx:~/marketplace/webapp# **_npm install_**


npm ERR! code 1
npm ERR! path /root/marketplace/webapp/node_modules/keccak
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@10.24.1 | linux | x64
npm ERR! gyp info find Python using Python version 3.6.9 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [ '/root/.nvm/versions/node/v10.24.1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/root/marketplace/webapp/node_modules/keccak/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/root/.nvm/versions/node/v10.24.1/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/root/.cache/node-gyp/10.24.1/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/10.24.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/root/.nvm/versions/node/v10.24.1/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/10.24.1/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/root/marketplace/webapp/node_modules/keccak',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.' ]
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: not found: make
npm ERR! gyp ERR! stack     at getNotFoundError (/root/.nvm/versions/node/v10.24.1/lib/node_modules/npm/node_modules/which/which.js:10:17)
npm ERR! gyp ERR! stack     at Promise (/root/.nvm/versions/node/v10.24.1/lib/node_modules/npm/node_modules/which/which.js:57:18)
npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
npm ERR! gyp ERR! stack     at step (/root/.nvm/versions/node/v10.24.1/lib/node_modules/npm/node_modules/which/which.js:54:21)
npm ERR! gyp ERR! stack     at Promise (/root/.nvm/versions/node/v10.24.1/lib/node_modules/npm/node_modules/which/which.js:71:22)
npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
npm ERR! gyp ERR! stack     at subStep (/root/.nvm/versions/node/v10.24.1/lib/node_modules/npm/node_modules/which/which.js:69:33)
npm ERR! gyp ERR! stack     at isexe (/root/.nvm/versions/node/v10.24.1/lib/node_modules/npm/node_modules/which/which.js:80:22)
npm ERR! gyp ERR! stack     at /root/.nvm/versions/node/v10.24.1/lib/node_modules/npm/node_modules/isexe/index.js:42:5
npm ERR! gyp ERR! stack     at /root/.nvm/versions/node/v10.24.1/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
npm ERR! gyp ERR! System Linux 4.15.0-121-generic
npm ERR! gyp ERR! command "/root/.nvm/versions/node/v10.24.1/bin/node" "/root/.nvm/versions/node/v10.24.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /root/marketplace/webapp/node_modules/keccak
npm ERR! gyp ERR! node -v v10.24.1
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-05-20T02_19_13_772Z-debug.log

**Comment by nachomazzara** [comment]
What is your node and npm version?
Have you created the .env file with `/webapp/.ci/.env.dev`?

**Comment by mobin-ux** [comment]
> What is your node and npm version?
> Have you created the .env file with `/webapp/.ci/.env.dev`?


node version
v14.17.0

npm version
6.14.13


I have not changed anything in the `/webapp/.env` file
But I created that file with the following commands:
```
$ mv .env.example .env
$ vi .env
```

@nachomazzara

**Comment by nachomazzara** [comment]
Not sure what is the error, I can not reproduce the log that you have posted. 

What is not working at your end? can you provide more context?

**Comment by mobin-ux** [comment]
> Not sure what is the error, I can not reproduce the log that you have posted.
> 
> What is not working at your end? can you provide more context?

I do not know either :(
Can you install **marketplace** Source on the new server?
Because maybe I did the installation wrong

**(I will give you the server myself)**

I just want to be able to see NFT products on the home page

@nachomazzara

**Comment by nachomazzara** [comment]
I have working at my end. In order to help you, I need more context

**Comment by mobin-ux** [comment]
> I have it working at my end. In order to help you, I need more context

What should I do now?

**Comment by mobin-ux** [comment]
> I have it working at my end. In order to help you, I need more context

I'm really confused
The source used to work well and display NFTs
But it does not show now
@nachomazzara

**Comment by mobin-ux** [comment]
look at this
https://marketplace-clie95jdp-decentraland1.vercel.app/

I sent this to you from the section (https://github.com/decentraland/marketplace/deployments/activity_log?environment=Preview)

The same goes for me and does not show NFTs :(

**Comment by mobin-ux** [comment]
> I have it working at my end. In order to help you, I need more context

look at this
https://marketplace-clie95jdp-decentraland1.vercel.app/

I sent this to you from the section (https://github.com/decentraland/marketplace/deployments/activity_log?environment=Preview)

The same goes for me and does not show NFTs   :(

@nachomazzara

**Comment by nachomazzara** [comment]
Have you copied the `.env.dev` file into `webapp/.env` ?

**Comment by mobin-ux** [comment]
> webapp/.env

Hello
My problem was solved
I copied the **.env.dev** file to **webapp /.env**
