### ISSUE TITLE
API not returning all transactions

### ISSUE THREAD

**Issue by decentraliser** [decentraland/marketplace#294]
Hi, 

I fetched all publications from the API with the call `GET /parcels`, and while sample checking I noticed that some transactions are not here.

For example this famous transaction on[ the land 39, 62](https://market.decentraland.org/39/62/detail) when it had been sold for 25 MANA.
This transaction [is supposed to be in the block 5,666,187](https://etherscan.io/block/5666187)

However, the API call `GET /parcels` does not return a transaction for this block, and returns no transaction for this particular LAND ([see here](https://api.decentraland.org/parcels?sort_order=desc&offset=1550&limit=50))

But by using the call `GET /parcels/:x/:y` , all transactions from this LAND are here.
[https://api.decentraland.org/parcels/39/62/publications](https://api.decentraland.org/parcels/39/62/publications)

Is that normal that the API call `GET /parcels` does not return all transactions ? 

Thanks

**Comment by abarmat** [comment]
The `/parcels` endpoint only gets you the last active publication for each parcel, where the `/parcels/:x/:y/publications` gets you all the publications for a certain parcel (historic included)

**Comment by decentraliser** [comment]
Yes, I know, But in this example, no tx for the LAND 39/62 is returned when i call the parcel API call'

**Comment by Sm00g15** [comment]
are there any tutorials on how to buy LAND programmatically?

**Comment by Sm00g15** [comment]
@cazala how can we interact with the LAND contract to buy LAND programmatically?

**Comment by cazala** [comment]
you can use [decentraland-eth](https://github.com/decentraland/decentraland-eth) to interact with our contracts from javascript:

```js
import { eth, contracts } from 'decentraland-eth'

const marketplace = new contracts.Marketplace('0xdeadbeef' /*address*/)

async function main() {
  await eth.connect({
    provider: 'http://localhost:8545',
    contracts: [
      marketplace
    ]
  })

  await marketplace.executeOrder(assetId, eth.utils.toWei(price))
}

main()
```

You will need a running eth node in localhost:8545 with an unlocked account for this in order to work

**Comment by cazala** [comment]
You can get de addresses for all our contracts from https://contracts.decentraland.org/addresses.json

**Comment by Sm00g15** [comment]
Awesome thanks man! Am I able to use an Infura node as a provider?

**Comment by cazala** [comment]
Using infura's url as provider should work fine (ie `provider: 'https://ropsten.infura.io/'`)

**Comment by Sm00g15** [comment]
Alright and final question, where can I find the all the methods that can be run on the market place function? 

You’ve shown the marketplace.executeOrder(), and now I’m just looking for documentation  or a place to find out all the methods that can be executed?

**Comment by Sm00g15** [comment]
contracts.Marketplace is not a constructor ; 

I’m hitting this error when running the below code. Any ideas what why that’d be?

**Comment by Sm00g15** [comment]
```
const eth = require('./node_modules/decentraland-eth/dist')
const contracts = require('./node_modules/decentraland-eth/dist/contracts')

const marketplace = new contracts.Marketplace("0x80faa2b517b84a5aec1078d3600eab4c0b3aff56")

async function main() {
  await eth.connect({
    provider: 'https://ropsten.infura.io/LqcsWaKmLHMjTJP8k1AU',
    contracts: [
      marketplace
    ]
  })

  console.log('marketplace is connected')
}

main()
```

Here's my code above, and I keep hitting this error: 
`
(node:5248) UnhandledPromiseRejectionWarning: TypeError: eth.connect is not a function`

Any idea why that'd be the case? I tried using the Import function and kept getting `unexpected token import` . Any ideas on how to fix this?

**Comment by Sm00g15** [comment]
sweeeeet, that all works great. Now how can I test purchasing a property with ropsten? Is there a way to pull available parcels on the Ropsten network through the API?

**Comment by Sm00g15** [comment]
and if I put my private keys in that same file will I able to do automatic transactions running from an infura provider without having to unlock my account?

**Comment by Sm00g15** [comment]
@decentraliser you should close this issue if you're done with it. thanks @cazala and @NicoSantangelo  for the help!

**Comment by decentraliser** [comment]
Right on, thanks !
