### ISSUE TITLE
When running the executeOrder function I get new BigNumber() not a number

### ISSUE THREAD

**Issue by Sm00g15** [decentraland/marketplace#296]
So after feeding data into my executeOrder function from the marketplace API I'm running into this error: 
`BigNumber Error: new BigNumber() not a number: 25,150`

I'm using executeOrder on the marketplace contract by feeding the asset_id (25,150 in this case) as the first argument and the price in MANA (5000 in this case) as the second argument. Is this the proper way to use this function?

**Comment by Sm00g15** [comment]
Seems that by converting the asset_id to a number and removing the comma I've fixed the BigNumber issue, but now I'm getting an error of: 

```Error: invalid address```

**Comment by nachomazzara** [comment]
The `assetId`  from  `executeOrder(uint256 assetId, uint256 price)` is the result of calling [encodeTokenId](https://github.com/decentraland/land/blob/master/contracts/land/LANDRegistry.sol)

So it should looks like:

```javascript
const landId = await land.encodeTokenId(25, 150)
await market.executeOrder(landId, 10000)
```
