### ISSUE TITLE
Can't buy an item in the marketplace if I have the same amount of MANA as the item price

### ISSUE THREAD

**Issue by nachomazzara** [decentraland/marketplace#302]

**Comment by nicosantangelo** [comment]
To fix in Decentraland UI, it's a problem with rounding numbers
![image.png](https://images.zenhubusercontent.com/601dcbd9715e60c791100933/6485427f-67f3-459a-9527-d8bf815bf4a6)

**Comment by cazala** [comment]
Fixed in decentraland-ui
