### ISSUE TITLE
cant to start webapp

### ISSUE THREAD

**Issue by yanis7774** [decentraland/marketplace#31]
When trying to launch webapp

Failed to compile
./src/Routes.js
Module not found: Can't resolve 'components/GoogleAnalytics' in '/Users/hsbs/DCL/marketplace1/webapp/src'
This error occurred during the build time and cannot be dismissed.

**Comment by cazala** [comment]
did you set up your `.env` file?

**Comment by NicoSantangelo** [comment]
@yanis7774 did #30 work for you?

**Comment by cazala** [comment]
i'm closing this for now due to inactivity
