### ISSUE TITLE
executeOrder function stops iterating in loop

### ISSUE THREAD

**Issue by Sm00g15** [decentraland/marketplace#311]
@cazala I'm having an interesting issue with the executeOrder function. Whenever I run it in a loop my loop stops iterating after one iteration with the function. Yet when I remove that function and just add a console.log it completes the loop just fine. 

Do you think this is an issue with metamask and the async nature of executeOrder? Maybe sleeping a bit will help it?

**Comment by abarmat** [comment]
`executeOrder` is part of the Marketplace contract. Could you please tell me what are you implementing? Maybe you should await the call to the contract function.

**Comment by Sm00g15** [comment]
^ i've fixed this, it's all good
