### ISSUE TITLE
Coding Guidelines Proposal

### ISSUE THREAD

**Issue by cazala** [decentraland/marketplace#32]
This is just a proposal to keep code consistent. It's intended to be a living document, most of the conventions that I'm writing here are the ones we are already using, but I just wanted to have them written down. Nothing is written in stone tho, if there's something you don't like lets use this issue to discuss it.

### 1.1 Using `PureComponent`s

We should use `PureComponent`s for all our components, except when they depend on the `context`. They work in the same way as regular `Component`s but they implement a `shouldComponentUpdate()` with a shallow prop and state comparison. This can save tons of unnecessary renders. 

ie:

```jsx
const Stateless = () => {
  console.log('stateless')
  return <p>Stateless</p>
}

class Pure extends React.PureComponent {
  render() {
    console.log('pure')
    return <p>Pure</p>
  }
}
```

You will notice that the `Stateless` component triggers its render function on every keystroke while the pure doesn't:

![pure-stateless](https://user-images.githubusercontent.com/2781777/34625919-51923b08-f239-11e7-8f75-2ea120a3aded.gif)

### 1.2 Avoid creating stuff inside the `render()` function

The `render()` function is one of the most called functions, so we should try to minimize the memory footprint by not creating objects or functions. Also, since we use `PureComponent`s if we create new objects, that will trigger unnecessary renders in the components down the tree because it will make the shallow props comparison to fail.

**BAD:**

```jsx
class Options extends React.PureComponent {
  render() {
    const options = ['A', 'B', 'C']
    return <select options={options}>
  }
}
```

**GOOD:**

```jsx
const options = ['A', 'B', 'C']
class Options extends React.PureComponent {
  render() {
    return <select options={options}>
  }
}
```

Same thing applies for functions:

**BAD:**

```jsx
class Input extends React.PureComponent {
  ...
  render() {
    return <input value={this.state.value} onChange={e => this.setState({ value: e.target.value }}>
  }
}
```

**GOOD:**

```jsx
class Input extends React.PureComponent {
  ...
  handleChange = e => this.setState({ value: e.target.value }}
  render() {
    return <input value={this.state.value} onChange={this.handleChange}>
  }
}
```

### 1.3 Use memoized selectors

Using memoized selectors (like `reselect`) helps preventing unnecessary computation and since the 
reference is memoized (it returns the same reference), when we combine this with 
`PureComponent` that will also save tons of unnecessary renders.

**BAD:**

```js
export const getList = state => {
  const books = getBooks(state)
  const authors = getAuthors(state)
  return Object.keys(books)
  .map(bookId => {
    const book = books[bookId]    
    return {
      ...book,
      author: authors[book.authorId]
    }
  })
}
```

**GOOD:**

```js
export const getList = createSelector(
  getBooks,
  getAuthors,
  (books, authors) => Object.keys(books)
    .map(bookId => {
      const book = books[bookId]
      return {
        ...book,
        author: authors[book.authorId]
      }
    })
)
```

### 2.1 Components

Naming conventions:

- **callback props**: start with `on` + the name of the event, ie: `onMouseMove`, `onOpen`, `onChange`.

- **boolean props**: start with `is` or `has`, ie: `isLoading`, `hasError`.

- **handlers**: start with `handle` + the name of the event, ie: `handleMouseMove`, `handleOpen`, `handleChange`.

File structure:

Each file contains a single component which is exported as `default`

### 2.2 Containers

Containers have no jsx, they just import the component they will connect, they have two functions `mapState` and `mapDispatch` (optionally `mergeProps` if needed), and finally they export the HOC as `default`, ie:

```js
import { connect } from 'react-redux'
import Component from './Component'

const mapState = state => {
...
}

const mapDispatch = dispatch => {
...
}

export default connect(mapState, mapDispatch)(Component)
```

### 2.3 Reducer

File structure

1. Start with an `INITIAL_STATE`

2. Export a function `reducer` as default

3. Finally export selectors

For selector we use lambdas, we use `get` as prefix unless the return value is a boolean, in that case we use `is`/`has`. Unless the state is too simple, add a `getState` selector that returns the root of the state of this reducer, and let the other selectors depend on it (so it's easier to refactor the shape of the application state later).

Example:

```js
import { SOMETHING } from './actions'

const INITIAL_STATE = {
  something: 1
}

export default function reducer(state = INITIAL_STATE, action) {
  switch(action.type) {
    case SOMETHIG:
      return {
        …state,
        something: action.value
    }
    case default:
      return state
  }
}

// --

export const getState => state => state.path.to.reducer
export const getSomething = state => getState(state).something
```

### 2.4 Actions

Export all action types as constants at the beginning, then all the action creators as functions

Example:

```js
const SOMETHING = 'Something'

function doSomething(value) {
  return {
    type: SOMETHING,
    value
  } 
}
```

For async actions, use the prefix `_REQUEST`, `_SUCCESS` and `_FAILURE`

```js
export const FETCH_SOMETHING_REQUEST = '[Request] Something'
export const FETCH_SOMETHING_SUCCESS = '[Success] Something'
export const FETCH_SOMETHING_FAILURE = '[Failure] Something'
```

### 2.5 Sagas

export your saga as `default`, then place all the handlers below

```js
import { 
  FETCH_SOMETHING_REQUEST,
  FETCH_SOMETHING_SUCCESS,
  FETCH_SOMETHING_FAILURE
} from './actions'

export default function* saga() {
  yield takeLatest(FETCH_SOMETHING_REQUEST, handleFetchSomething)
}

function* handleFetchSomething(action) {
  try {
    const something = yield call(() => fetch(...))
    yield put({ type: FETCH_SOMETHING_SUCCESS, something })
  } catch (error) {
    yield put({ type: FETCH_SOMETHING_FAILURE, error: error.message })
  }
}
```

The pattern that we use to trigger actions from a different domain is always `put`ing the action, never `take`ing it.

**BAD:**

```js
// modules/something/sagas.js
import { LOGIN_SUCCESS } from 'modules/login/actions'

export default function* saga() {
  yield takeLatest(LOGIN_SUCCESS, handleLoginSuccess)
}

function* handleLoginSuccess(action) {
  yield put({ type: FETCH_SOMETHING_REQUEST })
}
```

**GOOD:**

```js
// modules/login/sagas.js
import { FETCH_SOMETHING_REQUEST } from 'modules/login/actions'

export default function* saga() {
  yield takeLatest(LOGIN_REQUEST, handleLoginRequest)
}

function* handleLoginRequest(action) {
  try {
    ...
    yield put({ type: LOGIN_SUCCESS })
    yield put({ type: FETCH_SOMETHING_REQUEST })
  } catch (error) {
    yield put({ type: LOGIN_FAILURE, error: error.message })
  }
}
```

**Comment by menduz** [comment]
I'd add a rule to avoid export default, I've been doing that during the past months and if you use Atom or VSCode the editor helps you a lot fixing problems.

Bonus points: You even get autocomplete at this import {/*here*/} from "./foo"; cursor location. Gives your developers a bit of wrist relief.

Bonus points: Better commonJs experience. With default there is horrible experience for commonjs users who have to const {default} = require('module/foo'); instead of const {Foo} = require('module/foo')

**Bonus points**: You don't get typos like one dev doing `import Foo from "./foo"` and another doing `import foo from "./foo"`

**Bonus points**: Auto import quickfix works better. You use Foo and auto import will write down `import { Foo } from "./foo"` cause its a well defined name exported from a module.

**Bonus points**: Reexporting is unnecessarily hard. Reexporting is common for the root index file in npm packages e.g. `import Foo from "./foo"; export { Foo }` (with default) vs. `export * from "./foo"` (with named exports).

See also: https://blog.neufund.org/why-we-have-banned-default-exports-and-you-should-do-the-same-d51fdc2cf2ad

**Comment by NicoSantangelo** [comment]
@menduz +1
I don't think default is *that* bad but I still think it's a good idea if we keep the code consistent.

I used to do this religiously and but stopped to convey some kind of hierarchy on the exported objects, for example having a `/Parcel` folder with:

```
Parcel/
├── Parcel.js
├── Parcel.service.js
├── Parcel.spec.js
├── coordinates.js
└── index.js
``` 

And then being able to import the `Parcel.js` file by default. But it never really worked that well

**Comment by michaltakac** [comment]
+1
We could also make separate repo with such guidelines. Like Airbnb Javascript style guide. Would help across projects to stay consistent.

**Comment by menduz** [comment]
Merged in decentraland/standards
