### ISSUE TITLE
Loading more does not work

### ISSUE THREAD

**Issue by nachomazzara** [decentraland/marketplace#323]
Go to a user profile, then click on the assets (e.g: wearables), and if `load more` is there, click on it. 
Current behavior: not loading next items.
Expected behavior: load next items.

**Comment by cazala** [comment]
I can't reproduce it :(

![Kapture 2021-06-10 at 14.33.04.gif](https://images.zenhubusercontent.com/5e5d3db4c9cab6a330a30e9a/52de5acd-2fb0-4b60-b771-987c7a53ed00)
