### ISSUE TITLE
Analyze how viable it is to combine types between Item and NFT

### ISSUE THREAD

**Issue by nicosantangelo** [decentraland/marketplace#327]
TODO
- [ ] Item type
- [ ] ItemOptions type

**Comment by nicosantangelo** [comment]
Also check the nft-server to see how easy it is to combine them there too

**Comment by cazala** [comment]
Backend:
---
Add `Item` type to source component.
Add `ItemOptions` type: sort (name, price, newest), text search, filter by (collection/contract, rarity, gender).
Add `fetchItems` to source component interface, it should return a `ItemResult`, consisting of an `Item` and its sorting metadata (without an Order), and `fetchItems(subgraph, options): Promise<ItemResult[]>` in constructor.
Namespace `fetch` and NFT related types and methods with "NFT".
Handle `fetchItems` aggregation from aggregator component (might need different sorting logic)
Handle `fetchItems` logic from browse component.
Add endpoint `/items/browse` and connect it to handler
Rename `/browse` endpoint to `/nfts/browse`

**Comment by nicosantangelo** [comment]
Add the concept of `asset` so we can introduce `AssetType = { NFT = 'nft'; ITEM = 'item' }`. We can use this later on the BrowsePage and as a querystring filter.

Rename `browse` action to `browseNFTs`. Add a `browseItems` action

Add an item module with it's actions/sagas/selectors
- Add an `itemAPI` even though it's using the same server, adding the types and methods it needs
- The new buy logic should be there too

Add a `ItemBrowse` analogous to `NFTBrowse`,  decide on `BrowsePage`. Consider adding the components it uses inside the same folder. We could also move components like `NFTCard` there if they're not being used anywhere else (`HomePage` comes to mind).

Update AccountPage to use the new ItemBrowse 

Add a new detail URL changing `/contract/:address/tokens/:tokenId` to `/contract/:address/item/:itemId`

Consider clearing the URL query string when moving from NFT to Item to avoid weird states

Sidebar:
- If you're filtering by account, you need to show Land+Wearables (everything)
- If you're in primary/secondary sales the sections are mutually exclusive

ItemBrowse (probable additions)
- ItemCard
- ItemFilters: Maybe we can reuse things like the Components inside Decentraland's `NFTFilter`
- ItemList: We can maybe reuse this logic if it fits, extracting the current NFTList logic

Consider adding a new Slideshow to the `HomePage`
