### ISSUE TITLE
Compiled with warnings.

### ISSUE THREAD

**Issue by Minddit** [decentraland/marketplace#348]
what have i missed here?
Compiled with warnings.

src/components/NFTBrowse/NFTBrowse.tsx
  Line 45:6:  React Hook useEffect has missing dependencies: 'address', 'onlyOnSale', 'vendor', and 'view'. Either include them or remove the dependency array  react-hooks/exhaustive-deps

src/components/SettingsPage/Authorization/Authorization.tsx
  Line 39:25:  Array.prototype.some() expects a value to be returned at the end of arrow function  array-callback-return

src/modules/ui/types.ts
  Line 14:13:  'View' is already defined  @typescript-eslint/no-redeclare

src/modules/vendor/routing/types.ts
  Line 13:14:  'Section' is already defined  @typescript-eslint/no-redeclare

src/modules/vendor/types.ts
  Line 22:13:  'ContractName' is already defined  @typescript-eslint/no-redeclare

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

**Comment by nicosantangelo** [comment]
This was due to the project being newly migrated to hooks it should work correctly now :)
