### ISSUE TITLE
When seller is not owner no error is shown

### ISSUE THREAD

**Issue by EibrielInv** [decentraland/marketplace#430]
Probably related to https://github.com/decentraland/marketplace/issues/178 , some people is trying to buy this land, but Memamask don't show up, and no error is shown.

On the console the error is: `MetaMask - RPC Error: execution reverted: The seller is no longer the owner`

(-61,150)

https://market.decentraland.org/contracts/0xf87e31492faf9a91b02ee0deaad50d51d56d5d4d/tokens/115792089237316195423570985008687907832512760283463317768191732954575268741270

**Comment by arorakanav** [comment]
Hey @nachomazzara, I would like to work on this issue. can I get a reference to get started?

**Comment by nachomazzara** [comment]
Yeah! go ahead
