### ISSUE TITLE
Validate addresses at /account

### ISSUE THREAD

**Issue by nachomazzara** [decentraland/marketplace#447]
We need to validate if the address passed is valid.

https://market.decentraland.io/accounts/pepe should not be valid.

https://market.decentraland.io/accounts/0x4e54d0b254113b381e5fbdb2488570f2cdf0ac87 should be valid

**Comment by mercush** [comment]
Addressing this rn. Will likely have pr by end of day.

**Comment by juanmahidalgo** [comment]
Addressed & deployed to prod.
