### ISSUE TITLE
Running Marketplace / WebApp / npm start / error: react-scripts not found + CI is not recognized

### ISSUE THREAD

**Issue by loveTSloveNET** [decentraland/marketplace#464]
Hello Sir! 🙂

I was trying to install a fresh clone, and it bounces back with a "react-scripts not found"

**ON MY SERVER:** Ubuntu 20.04
**Step 1:** Setting up variables
```
cd /var/www/marketplace/webapp
mv .env.example .env
nano .env
```
**Step 2:** installing (but it gets killed in the end)
![image](https://user-images.githubusercontent.com/24850331/142737362-47a9fe73-a7ac-43a6-8367-288aa8a54fc9.png)

**Step 3:** starting
![image](https://user-images.githubusercontent.com/24850331/142737230-d47bb121-e55d-4c62-87dc-d4cf1dbf9c47.png)

**ON MY LOCAL PC:** Windows 10
**Step 1:** Setting up variables + installing
`Renaming the .env.exampe to .env manually`

**Step 2:** starting
`npm start`
[http://localhost:3000/](http://localhost:3000/)
Works fine

**Step 3:** And when i build it i get a CI is not recognized message
`npm run build` 
![image](https://user-images.githubusercontent.com/24850331/142737618-4ba15103-2c02-41d1-a665-389aa40f0df6.png)

About the server not starting:
Tried to delete the modules and reinstall like suggested around internet. Bust still not changing the outcome.

About the local machine not building:
Any workaround? Or any hint?

Thanks! 😎🙏

**Comment by kongsiyu** [comment]
Probably because of your NodeJS version，my development environment has the same problem, but i don't have this problem on other computers：
npm: '7.18.1',
node: '16.4.2',

**Comment by nicosantangelo** [comment]
@kongsiyu  is correct! this is probably due to the node version. If you're running a newer npm version and it throws dependency errors you can avoid them with `--force` too

I'm closing this for now, but feel free to reach out again and thanks again @kongsiyu
