### ISSUE TITLE
Running Marketplace / indexer / Missing script: Codegen & ropsten/mainnet

### ISSUE THREAD

**Issue by loveTSloveNET** [decentraland/marketplace#465]
Hello Sir! 🙂

Was trying to start it both on my Test Ubuntu Server and on My Local Windows PC

**PROBLEM:**
And it bounces back with a message telling: Missing script: codegen
![image](https://user-images.githubusercontent.com/24850331/142737997-78581fe3-fd57-40ca-9fd8-101d0682a4d6.png)

And here the log:
![image](https://user-images.githubusercontent.com/24850331/142738091-c4c38123-c727-4e7c-9073-3314f2372766.png)

Any idea on what is going on?
Appreciate it!

Thanks! 😎🙏

**Comment by nicosantangelo** [comment]
Hey! real late response but for prosperity.
It seems like you were running the indexer commands on the wrong folder. You `cd`ed on `webapp` instead of `indexer`

```bash
cd ../indexer
npm install
# commands
```

should've fixed the issue.

Sorry again for taking literally forever
