### ISSUE TITLE
Deselect the `my store` tab when seeing a collection

### ISSUE THREAD

**Issue by nachomazzara** [decentraland/marketplace#517]
By using this link https://market.decentraland.org/collections/0xb96697fa4a3361ba35b774a42c58daccaad1b8e1 we should deselect the `My store` tab by either do not select any tab or by selecting the collectibles one.

**Comment by nishit-g** [comment]
Hey @nachomazzara , can I take this up ?

**Comment by nachomazzara** [comment]
sure @nishit-g
