### ISSUE TITLE
Redirect and keep to the desired page when visiting auth pages

### ISSUE THREAD

**Issue by nachomazzara** [decentraland/marketplace#530]
There are two undesired behaviour here

### My assets

Visiting any page under my assets directly:
https://market.decentraland.org/account?assetType=nft&section=wearables&vendor=decentraland&page=1&sortBy=newest&onlyOnSale=false&viewAsGuest=false

you'll get redirected to:
https://market.decentraland.org/account?section=collections

even if you're logged in.

### Buy/Bid/etc

If you're trying to perform an auth operation like bidding an item before logging in, after picking a wallet you'll get redirected to https://market.decentraland.org/account?section=collections leaves you needing to search for what you wanted to do before

**Comment by meelrossi** [comment]
This was already implemented with new auth dapp
