### ISSUE TITLE
Invalid MakersPlace API URL "undefined"

### ISSUE THREAD

**Issue by puomlion** [decentraland/marketplace#532]
I am just trying to run the project and I'm getting this error message: Invalid MakersPlace API URL "undefined"
Any help, please?

**Comment by fzavalia** [comment]
Have you copied `.env.example` into `.env`?

**Comment by puomlion** [comment]
> Have you copied `.env.example` into `.env`?

I don't have any file like that in the project folder

**Comment by nicosantangelo** [comment]
This probably was an env problem but after [this PR](https://github.com/decentraland/marketplace/pull/680) vendors like MakersPlace do not exist anymore and after [this one](https://github.com/decentraland/marketplace/pull/693) we're no longer using `.env`

Sorry for the massive delay tho and feel free to open another issue if any problem arises
