### ISSUE TITLE
Newest Land card gets cut in half on laptop screen size

### ISSUE THREAD

**Issue by Sm00g15** [decentraland/marketplace#535]
![screen shot 2018-10-09 at 10 22 54 am](https://user-images.githubusercontent.com/14209806/46634429-6b03ec00-cbad-11e8-9acd-f434e983b5fe.jpg)

**Comment by abarmat** [comment]
Hey thank you for reporting this problem. 

There is an upcoming revamp of the Marketplace UI that you can follow at https://github.com/decentraland/marketplace/projects/9

We are fixing this along with some other issues.

**Comment by nicosantangelo** [comment]
Hey, I'm closing this because it's working as intended (via horizontal scroll) and because it's likely to change.

Thanks for the report!
