### ISSUE TITLE
Fix toasts not closing after timeout defined timeout.

### ISSUE THREAD

**Issue by fzavalia** [decentraland/marketplace#535]
![image.png](https://images.zenhubusercontent.com/5ea09af31c23030cb8e249b8/d32d80b4-4c73-4542-b932-432c6f9dff7c)

Find out and fix toasts that are not being closed on timeout and can only be closed by clicking the X.

If the issue cannot be solved directly in the marketplace, check the `ToastProvider` in decentraland-dapps or the `Toast` component in decentraland-ui

**Comment by cazala** [comment]
fixed in decentraland-ui
