### ISSUE TITLE
After put a Estate on sale I get an error on the console and the Marketplace Estate tab breaks

### ISSUE THREAD

**Issue by abarmat** [decentraland/marketplace#550]
<img width="803" alt="screen shot 2018-10-09 at 18 58 31" src="https://user-images.githubusercontent.com/140773/46701499-3a947000-cbf6-11e8-97c4-87ed98178059.png">

**Comment by NicoSantangelo** [comment]
Pretty sure this is fixed on https://github.com/decentraland/marketplace/commit/d441380797698f9d69f6740ea99e634af3396ae6

**Comment by abarmat** [comment]
Fixed
