### ISSUE TITLE
What method can I call to get parcel data?

### ISSUE THREAD

**Issue by Sm00g15** [decentraland/marketplace#565]
I'm currently working with the Registry contract and after running this keep erroring out:

```
 const token =  registryContract.methods.encodeTokenId(27, -125).call()
  token.then(results => {
          registryContract.methods.tokenMetadata(results)
          .then(res => console.log(res))
          .catch(err) => console.error(err))
          })
.catch(err => console.error(err));
```

This is my error: 
`{ Error: invalid number value (arg="assetId", coderType="uint256", value=9.527906273786277e+39)`

a) is this the right method to be calling on the contract to get parcel data?
b) If it is the right method, how can I pass through the proper value to the method to get a response?

@cazala any ideas?

**Comment by Sm00g15** [comment]
I've also tried this IIFE, and my result comes back blank. 

```
(async () => {
  const data = await registryContract.methods
    .landData(-27, 125)
    .call((err, res) => console.log("token data: " + res));
})();
```

**Comment by Sm00g15** [comment]
I've also tried this: 

```
  const decode = await registryContract.methods
    .ownerOfLand(27,-125)
    .call((err, res) => console.log(res));
```
and all I get back is: 0x0000000000000000000000000000000000000000

**Comment by Sm00g15** [comment]
@NicoSantangelo would this be because the contract addresses have changed?

**Comment by abarmat** [comment]
Hey, what library are you using to interact with the contracts? Can you send me a snippet with that I could run to help you find the problem?

**Comment by Sm00g15** [comment]
@abarmat this can be closed now. I found out that I had to have the registry ABI locally and then call the proxy address when instantiating a contract. Thanks for the follow up.
