### ISSUE TITLE
Show "Not enough Mana" error message when user has 0 polygon mana and tries to buy

### ISSUE THREAD

**Issue by nachomazzara** [decentraland/marketplace#578]
@nicorajco commented on [Mon Mar 14 2022](https://github.com/decentraland/account/issues/197)

---

@nicorajco commented on [Mon Mar 14 2022](https://github.com/decentraland/account/issues/197#issuecomment-1067220281)

At the moment, when trying to buy an item and not having enough Polygon Mana (but more than 0), this is the error showned:
![image.png](https://images.zenhubusercontent.com/617ffbccd0621667f37f36b9/d4824dcb-912d-4beb-ae04-202f5bf49924)

But, if the user has 0 Polygon Mana, instead of that error, this is what the user sees now:
![image.png](https://images.zenhubusercontent.com/617ffbccd0621667f37f36b9/a3c885e0-1350-4eb1-ae2c-4aebcec05656)

The second error should not be that. Instead, we should show the first one. It wouldn't matter if the user has 0 polygon mana or 1. If they don't have enough Polygon Mana, the error should be the same.

---

@nicorajco commented on [Mon Mar 14 2022](https://github.com/decentraland/account/issues/197#issuecomment-1067221805)

Plus: if we could say "Polygon MANA" instead of just "MANA" for items that are in that network, it would be great :) 
If not, we can live with that.

**Comment by nicorajco** [comment]
Plus 2: if possible, add this legend at the end "Swap MANA" with a link to [Account](https://account.decentraland.org/). 

![image.png](https://images.zenhubusercontent.com/617ffbccd0621667f37f36b9/a63d6d75-6dfb-4fd3-8908-21797710f232)

**Comment by marian160** [comment]
Talk to a Polygon Dev on the [Live support page](https://forummaticnetwork.org/) so that your issue can be looked into.

**Comment by Canopix** [comment]
Hi Decentraland team! 

I was checking this issue. 
I found that `order` is null on that page is `null` 

Should this property be null? 


The function `isInsufficientMANA` in `BuyPage.tsx` evaluates the following: 
```
const isInsufficientMANA = (
    wallet: Wallet,
    asset: Asset,
    order: Order | null
  ) =>
    !!order &&
    wallet.networks[asset.network].mana < +fromWei(order.price, 'ether')
```

In this case, if there is not an order, so can not check the price and !!order returns false. 

I make a quick fix adding 
```if (wallet.networks[asset.network].mana === 0) return true;``` 

and this is the result for 0 MANA
<img width="919" alt="image" src="https://user-images.githubusercontent.com/4460417/160044591-22dcda33-224d-448f-9a9d-b0bd0c6150b6.png">


But I think this is not the best solution for this issue. 

My question here is: 

Why `order` is null at this point?

**Comment by nicosantangelo** [comment]
Hey @Canopix !

For what I can see the reason the `order` does not exist is that the `asset` is of type `ITEM`. That means that, rather than being traditionally "on sale", you'd be minting the item upon buying it. So if I'm not mistaken, the asset should have a `price` prop with the value we see rendered the (10 in this case).


Does that make sense?
