### ISSUE TITLE
i tried to transfer land, but get an error

### ISSUE THREAD

**Issue by yanis7774** [decentraland/marketplace#58]
Error: Error: [ethjs-rpc] rpc error with payload {"id":6980037569661,"jsonrpc":"2.0","params":["0xf8c90c8506fc23ac008261a894f87e31496a0439aa21e79f97bf1b6c2174e19a19c19ac77c02bc2b38b8ab712af79c9934a24a0258d3e1156dcaed25707c30d3ff75149ce66cb0b4e1194a32f8daea8daedd328"],"method":"eth_sendRawTransaction"} Error: intrinsic gas too low at TransactionStateManger.<anonymous> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:2216:39) at TransactionStateManger.g (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:69757:16) at TransactionStateManger.EventEmitter.emit (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:69673:17) at TransactionStateManger._setTxStatus (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:5488:14) at TransactionStateManger.setTxStatusFailed (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:5448:12) at TransactionController._callee6$ (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:2479:37) at tryCatch (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:20399:40) at Generator.invoke [as _invoke] (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:20633:22) at Generator.prototype.(anonymous function) [as throw] (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:20451:21) at step (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:18078:30) at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:18091:13 at <anonymous>
TRANSFER

**Comment by cazala** [comment]
@yanis7774 were you using MetaMask when this happened? Or did you do it using a Ledger? We are tracking a bug related to transferring LAND using Ledger Nano S.

**Comment by yanis7774** [comment]
@cazala metamask
