### ISSUE TITLE
Remember user scroll when back from Product Detail Page

### ISSUE THREAD

**Issue by nicorajco** [decentraland/marketplace#585]
PDP = Product Listing Page
PLP = Product Listing Page

When I’m at the PLP and click on any wearable to see the item in detail (I go to the PDP),and then I want to go BACK to the PLP, I’m always redirected to the top of the page. In this case, the user should get back to where they left in their scroll, not the top of the page.
Why? If I was scrolling for a while, I enter to the PDP and then want to go back to continue navigating the PLP, I have to scroll all the way down to where I was before to continue searching. It's annoying and it would be a better experience if the system remembers where I was standing in the scroll.

Note:
PDP: Product Detail Page, it's the detail page for a wearable. Example: https://market.decentraland.org/contracts/0x6f97ae3347a6a16a1e89d3560ae50df16781668e/items/0
PLP: Product Listing Page, it's the listing page of wearables. Example: https://market.decentraland.org/browse?assetType=item&section=wearables&sortBy=recently_reviewed

**Comment by meelrossi** [comment]
This is already fixed :) Closing the issue

**Comment by meelrossi** [comment]
This is already fixed :) Closing the issue
