### ISSUE TITLE
Add USD equivelent when listing parcels for sale

### ISSUE THREAD

**Issue by dafky2000** [decentraland/marketplace#591]
This may be a better option than preventing some arbitrary amount (1,000 MANA). Could be shown inline when entering the amount of MANA and could also be added the confirmation screen - showing the USD value will encourage users to double check their submission.

**Comment by abarmat** [comment]
Thank you for the suggestion! I'm closing this issue as we are tackling it in the following issue https://github.com/decentraland/marketplace/issues/594 included for a following release.
