### ISSUE TITLE
[Mobile] Fix lateral scroll and adjust width to margins

### ISSUE THREAD

**Issue by nicorajco** [decentraland/marketplace#597]
1. The screen does not adapt to the width of the device. For example, the pop up to sign in is not fully visible (if you turn the phone sideways -landscape-, you can see the full pop up with the X to close it). 
![](https://images.zenhubusercontent.com/617ffbccd0621667f37f36b9/ad896f05-64b8-453e-ab56-5bbd50df56c3)

2. When scrolling down, you can see that the content doesn't fit well within the laterals of the device screen (for example, when scrolling down the cards with wearables move a little) it is like margins are not fixed. 

To fix both issues, the width of the site should match the width of the phone, so everything is visible while on portrait and the scroll down is smooth. This was tested on an iPhone 12 mini

**Comment by meelrossi** [comment]
this doesnt apply anymore as we have rthe auth dapp
