### ISSUE TITLE
need help to install

### ISSUE THREAD

**Issue by Bwnm29** [decentraland/marketplace#609]
need help to install or document for install, now i'm stuck on subgraph,

**Comment by LautaroPetaccio** [comment]
Hi @Bwnm29, this a multi project repository, it contains the code for the Marketplace and for the graph used in the Marketplace. You can easily install and compile the Marketplace, but for the graph, you'll need your own key if you want to deploy it. You can always use one of the graphs that we've already deployed, those are in the README in the `indexer` directory.

**Comment by Bwnm29** [comment]
will have another post
