### ISSUE TITLE
error when deploy ropsten

### ISSUE THREAD

**Issue by Bwnm29** [decentraland/marketplace#611]
i got this error, i try to install it to my local machine window10

Error: spawn npx ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
PS D:\newdecen\indexer>

**Comment by nicosantangelo** [comment]
Hey there!

Could you provide more information on what you're doing? I'm not sure what command threw that error.

If I had to take a guess maybe you tried to run

```bash
npm run deploy:ropsten
```

without having run `npm install` first OR with an old version of node that does not have `npx` default in which case you'd probably have to run `npm install npx` first.

**Comment by juanmahidalgo** [comment]
Closing it for now, if you keep having issues, please create a new one, thanks!
