### ISSUE TITLE
Bug with Marketplace order cancellation

### ISSUE THREAD

**Issue by Sm00g15** [decentraland/marketplace#617]
I cancelled my LAND sale yesterday: 

![screen shot 2018-10-25 at 10 53 02 am](https://user-images.githubusercontent.com/14209806/47463967-48780100-d844-11e8-9679-6292030d8667.jpg)

Yet it still says that my land is for sale: 
![screen shot 2018-10-25 at 10 53 19 am](https://user-images.githubusercontent.com/14209806/47463972-5168d280-d844-11e8-8ef1-df51f02f319f.jpg)

And when I go to cancel again in the marketplace Metamask serves up an expensive transaction with this error: 

![screen shot 2018-10-25 at 10 54 57 am](https://user-images.githubusercontent.com/14209806/47464022-778e7280-d844-11e8-9112-9271cf329717.jpg)

**Comment by abarmat** [comment]
Hi, thank you for reporting this error. It seems it was due to an out-of-sync problem of the data we had in our DB and the one in the Ethereum blockchain. It should be fixed by now. I'll close this issue and re-open if it happens again.

**Comment by Sm00g15** [comment]
You're welcome, thank you for the fix and the heads up! I'll report again if I come across this or any other bugs.

**Comment by Sm00g15** [comment]
@abarmat ...While I have your attention...what is the best way to convert the PNG blob that the API sends to a usable picture?
