### ISSUE TITLE
Retrieving Past Events from the Legacy Marketplace throws error

### ISSUE THREAD

**Issue by Sm00g15** [decentraland/marketplace#641]
## 🎉 Description

I'm looking to use the Legacy Marketplace contract to backfill AuctionSuccessful data on my website 
However when I change the contract to the current marketplace abi and proxy address it works just fine. Any ideas what the issue could be?

* [X] 🐛 This is a bug report.
* [ ] 📈 This is a feature request.

## 📝 Details

I'm looking to use the Legacy Marketplace contract to backfill AuctionSuccessful data on my website with this code: 
```
const backfill = legacyMarketContract
  .getPastEvents("AuctionSuccessful", {
    fromBlock: 5284556,
    toBlock: "latest"
  }) 
``` 
(this uses the legacy and ABI and legacy address)
Everytime I keep hitting this error: 
```Error: CONNECTION ERROR: Couldn't connect to node on WS.```

However when I change the contract to the current marketplace abi and proxy address it works just fine. Any ideas what the issue could be?

```
- Connect to web3
- Provide legacy Abi and legacy contract address to instantiate a contract
- call get past events on contract with the event of AuctionSuccessful
```

**Comment by nachomazzara** [comment]
Hey!

- Which provider are you using?
- Did you try to use bigger `fromBlock`? sometimes you could get a timeout if there is a lot of events to return (mainnet)

Thanks

**Comment by Sm00g15** [comment]
Hey man! 
- I'm using Infura
- No I haven't tried fromBlock, but I'll give it a shot and give you some feedback here shortly.

**Comment by nachomazzara** [comment]
As you asked [here](https://github.com/decentraland/marketplace/issues/663). Is it good to close this one?
