### ISSUE TITLE
Reconsider Closed Issue #159 Ability to select an address other than the default on Ledger wallet

### ISSUE THREAD

**Issue by sean1000444** [decentraland/marketplace#646]
Is there any way to reconsider this or has there been any movement on this? It really seems like a regular use case for anyone using a Ledger as the addresses that Ledger Live and MEW generate are different from those which the Marketplace comes up with. This makes it quite a hassle to verify that the Marketplace's address is correct and accessible from one's Ledger then transfer ETH; MANA; and LAND to that address just to use the Marketplace.

**Comment by sean1000444** [comment]
Also on Agora I am unable to even see which address is being used when it connects to my Ledger.

**Comment by nachomazzara** [comment]
Hey, the way to go now is to import your ledger into Metamask https://medium.com/metamask/metamask-now-supports-ledger-hardware-wallets-847f4d51546
