### ISSUE TITLE
Decoding AssetId for Estates

### ISSUE THREAD

**Issue by Sm00g15** [decentraland/marketplace#663]
## 🎉 Description

Whenever I utilize the decodeTokenId() with an assetId from an estate I get back false X, Y values. 

**!!!!! This is more a request for help**
* [x] 🐛 This is a bug report.
* [ ] 📈 This is a feature request.

## 📝 Details

So I'm getting data from the blockchain and running it through the decodeTokenId function. Whenever it's an estate I'm not able to get the sale/creation data. How can I do that for an estate?

**Comment by nachomazzara** [comment]
Hey, you don't need to use `decodeTokenId` for Estate. 

The `id` for an Estate has not specially encoded as LAND. So you could get an Estate's order as:

`marketplaceContract.orderByAssetId(EstateRegistryContractAddress, Estate_ID_WITHOUT_DECODING)`

E.G:
`marketplaceContract.orderByAssetId('0x8e5660b4ab70168b5a6feea0e0315cb49c8cd539', 1)`

This will get the order for the Estate with Id `1`

**Comment by Sm00g15** [comment]
Cool, that works. How can I get the # of LAND available in that estate and their particular coordinates?

**Comment by nachomazzara** [comment]
## Get # of LAND by EstateId

```javascript
const stateSize = await estateContract.getEstateSize(EstateId)
```

## Get LAND coordinates by EstateId

```javascript
for (let i = 0; i < stateSize; i++) {
  // LAND
  const landId = await estateRegistry.estateLandIds(estateId, index)
}
```

**Comment by Sm00g15** [comment]
sweeet, thanks. And the estateContract is built up of the estate contract ABI and estate Proxy address correct?

**Comment by nachomazzara** [comment]
Yes!

**Comment by Sm00g15** [comment]
doooopeeee. all sorted, thank you!

**Comment by nachomazzara** [comment]
That estate doesn't have an open publication. 
Check the marketplace and try with an Estate on sale

**Comment by Sm00g15** [comment]
@nachomazzara I tried the above with an estate on sale and no dice. Sorry I'm just getting back to you, I'm just now circling around to this issue

**Comment by Sm00g15** [comment]
![screen shot 2019-01-07 at 5 14 02 pm](https://user-images.githubusercontent.com/14209806/50748731-afcc1b80-129f-11e9-8b9c-190014db147b.jpg)
![screen shot 2019-01-07 at 5 14 11 pm](https://user-images.githubusercontent.com/14209806/50748732-afcc1b80-129f-11e9-9d20-d405f4e46e40.jpg)

**Comment by nachomazzara** [comment]
You can’t use etherscan to check it cause you need to use the proxy contract address with the contract ABI.

You can do it with mycrypto

Marketplace proxy contract: `0x8e5660b4ab70168b5a6feea0e0315cb49c8cd539`

Marketplace contract: `0x19a8ed4860007a66805782ed7e0bed4e44fc6717`

**Comment by Sm00g15** [comment]
ahh okay, that fixed it! 

`marketplaceContract.orderByAssetId(EstateRegistryContractAddress, Estate_ID_WITHOUT_DECODING)`

I was using the address from the example just below this one ^, but it was the marketplace address! And thank you, mycrypto works way better!
