### ISSUE TITLE
Improve "No Results" state

### ISSUE THREAD

**Issue by cazala** [decentraland/marketplace#697]
## 🎉 Description

Instead of just showing a No Response text, add some more descriptions and shortcuts to recover from this state.
This needs to be reviewed for different use cases.

<img width="703" alt="Screen Shot 2022-06-15 at 13 41 52" src="https://user-images.githubusercontent.com/2781777/173880938-445b3a7b-d299-436b-9d77-eb0c193e9f8a.png">

* [ ] 🐛 This is a bug report.
* [x] 📈 This is a feature request.
Proposal: https://docs.google.com/presentation/d/1gmXqh6iSjeXZCEiAcG0uV75SnTKHJAjr2Egx82Vut7I/edit#slide=id.g133ba08418c_0_268

## 📝 Details

To complete this task we should:

- [ ] Change the "no results" copy to be `No results for "<query>" in <type>`
- [ ] Modify the "no results" state of the browse component to include a link to change the type (store or listing).
- [ ] Modify the "no results" state of the browse component to include a link to clear the filters and move to the top level section (ie. if the user was searching the "Head" category, move it to the "Wearables" category).

**Comment by meelrossi** [comment]
This was already implemented
