### ISSUE TITLE
Add link to listing from item pages that are not on sale

### ISSUE THREAD

**Issue by cazala** [decentraland/marketplace#698]
## 🎉 Description

Add a link to the browse page showing the listings for the item, if the items is not on sale (sold out is included in the "not on sale" status)

<img width="383" alt="Screen Shot 2022-06-15 at 13 48 34" src="https://user-images.githubusercontent.com/2781777/173882196-effcf310-f82a-4b16-b7f8-a974d2e0d3b8.png">

* [ ] 🐛 This is a bug report.
* [x] 📈 This is a feature request.

## 📝 Details

To complete this task we should:
- [ ] Add a button in the item page as shown in the wireframe that should only be visible if the item is not on sale, and when clicked it should take the user to the collectibles page, filtering listings for that item (use type=nft and `contractAddress` and `itemId` filters).

**Comment by meelrossi** [comment]
This was already implemented with new catalog
