### ISSUE TITLE
MANA Tooltip

### ISSUE THREAD

**Issue by cazala** [decentraland/marketplace#699]
## 🎉 Description

Add a tooltip to the mana component as shown in the wireframe:

<img width="700" alt="Screen Shot 2022-06-15 at 13 53 57" src="https://user-images.githubusercontent.com/2781777/173883176-c6478301-c3fc-4a43-bf3a-27525cbb5092.png">

* [ ] 🐛 This is a bug report.
* [x] 📈 This is a feature request.

## 📝 Details

To complete this task we should:

- [x] Add an optional `showTooltip` boolean prop to the `<Mana/>` component in [decentraland-ui](https://github.com/decentraland/ui) 
- [ ] Turn on the property in all the relevant places in the marketplace (item/nft cards, item/nft details, buy/sell/bid modals when it's not within an input)

**Comment by Chakravarthy7102** [comment]
@kevinszuchet  Add an optional showTooltip boolean prop to the <Mana/> component in [decentraland-ui](https://github.com/decentraland/ui) is completed 

PR: https://github.com/decentraland/ui/pull/318
