### ISSUE TITLE
Emotes aren't being showed anymore in the sales activity component

### ISSUE THREAD

**Issue by LautaroPetaccio** [decentraland/marketplace#715]
A discord user reported that the activity monitor is not displaying emotes:
![Screen Shot 2022-06-30 at 16 15 00](https://user-images.githubusercontent.com/1120791/176763057-b206ef80-fd4a-4fa4-94ea-0f074b0d290e.png)

To reproduce:
1. Sell one emote in the marketplace
2. Go to MyStore -> Sales and check that there's no emote in the activity.

**Comment by cazala** [comment]
The problem seems to be that the request only asks for the `wearable` category, so it's probably also missing the lands/estates/names as well, here's an example:

```
GET https://nft-api.decentraland.io/v1/sales?first=6&skip=0&sortBy=recently_sold&category=wearable&seller=0xb6e9c0a25aa6b10fa4fe0aa8d1097d2a6136bf98
```
