### ISSUE TITLE
Create the filters section

### ISSUE THREAD

**Issue by LautaroPetaccio** [decentraland/marketplace#719]
## 🎉 Description

To complete this task:
- [ ] Create the filter section as seen in the box number 3.
- [ ] The component must have the collapse all button to collapse all components inside of it.
- [ ] Filter the component's filters according to which category is selected (wearables, emotes, names or land)
- [ ] Create the collapsible components that will contain the filters.

![Untitled.png](https://images.zenhubusercontent.com/60d9e2eae14d1d56b7547674/59dd393e-4a28-490b-a450-b506c41345c0)

* [ ] 🐛 This is a bug report.
* [x] 📈 This is a feature request.

**Comment by meelrossi** [comment]
This is not required anymore
