### ISSUE TITLE
Create the store and the listing buttons

### ISSUE THREAD

**Issue by LautaroPetaccio** [decentraland/marketplace#724]
## 🎉 Description

To complete this task:
- [ ] Create the stores and listing buttons and place them in their new position as seen in the 1st red box.
- [ ] Consider the mobile version of the design.

Remember to ask for the icons.

![Untitled.png](https://images.zenhubusercontent.com/60d9e2eae14d1d56b7547674/850bbd6d-12ad-49ab-b4e3-16af9274ef76)

* [ ] 🐛 This is a bug report.
* [x] 📈 This is a feature request.

**Comment by meelrossi** [comment]
Solved in #729
