### ISSUE TITLE
Improve the empty search states

### ISSUE THREAD

**Issue by LautaroPetaccio** [decentraland/marketplace#731]
## 🎉 Description

To complete this task:
- [ ] Make empty states in searches actionable by following the description in the [notion](https://www.notion.so/decentraland/Filter-and-Search-Enhancements-1a2b1b3164f14060a5559dd214ef7304#7d2692de01f0422c926e6ceafb93ffc0).

![image.png](https://images.zenhubusercontent.com/638de9ed74b6880932257638/b4acd4f7-d4d2-4169-87b3-5037c6b9beaa)

* [ ] 🐛 This is a bug report.
* [x] 📈 This is a feature request.

**Comment by juanmahidalgo** [comment]
Closing since they will be address in #1217 and #1218
