### ISSUE TITLE
Reset the categories when searching for a new string

### ISSUE THREAD

**Issue by LautaroPetaccio** [decentraland/marketplace#732]
## 🎉 Description

To complete this task:
- [ ] Reset the categories when changing the search bar.

![ResetSearchCategory.gif](https://images.zenhubusercontent.com/60d9e2eae14d1d56b7547674/a9c9fefd-d4a8-4af4-99ef-d2c19d26642e)

* [ ] 🐛 This is a bug report.
* [x] 📈 This is a feature request.

**Comment by juanmahidalgo** [comment]
replaced by #1216
