### ISSUE TITLE
how to  change   the  Navbar  and   login   components? please

### ISSUE THREAD

**Issue by fuxuanhai** [decentraland/marketplace#734]
## 🎉 Description

* [ ] 🐛 This is a bug report.
* [ ] 📈 This is a feature request.

## 📝 Details

Describe the problem you have been experiencing in more detail. Include as much information as you think is relevant. Keep in mind that transactions can fail for many reasons; context is key here. Links to tx, screenshots are welcome.
Remember to not share sensible information

## 🔢 Steps To Reproduce Issue [ Good To Have ]

Please remember that with baby steps it's easier to reproduce the bug and it's much faster to fix it.

```
- Step 1
- Step 2
- Step 3
...
```

**Comment by LautaroPetaccio** [comment]
Closing it as this is not and issue.
