### ISSUE TITLE
List for rent modal

### ISSUE THREAD

**Issue by fzavalia** [decentraland/marketplace#747]
- [ ] First View

![image.png](https://images.zenhubusercontent.com/5ea09af31c23030cb8e249b8/f647ef38-7eb8-4e6a-9d9f-4a46a32b9580)

When the user clicks proceed:

If the user did not authorize the rental contract, sends authorization transaction, waits for it to complete, the goes to the second view.

- [ ] First View (for listing for rent again)

![image.png](https://images.zenhubusercontent.com/5ea09af31c23030cb8e249b8/4d92aaee-b0cf-4218-8e41-ebaab9f2d110)

This view shows instead of the previous one in the case that we are going through the list for rent again flow.

- [ ] Second View

![image.png](https://images.zenhubusercontent.com/5ea09af31c23030cb8e249b8/0de49043-d48e-48cd-bac5-d02c45425ae6)

The user has to input a price in MANA per day.

The user has to select any of the rent period options available. This is a multiple selection.

The user can select the expiration of the listing but a default of 1 month from now will be selected automatically.

Once all input fields are completed by the user, the list for rent button is enabled.

Clicking the list for rent button will take you to the third view.

- [ ] Third view

![image.png](https://images.zenhubusercontent.com/5ea09af31c23030cb8e249b8/54480ee9-02d5-450d-8d95-95ed151b2183)

The user can check the previously selected conditions in this view as confirmation.

Clicking on back will take the user to the second view.

Clicking on Confirm will prompt the user to sign the listing with their wallet.

Once signed, The signature and the listing is sent to the backend and a listing is officially created.

The modal is then closed and the user should see the asset detail page updated with the listing.

**Comment by LautaroPetaccio** [comment]
Closed issue in favor of #778 #777 #775
