### ISSUE TITLE
Edit listing modal

### ISSUE THREAD

**Issue by fzavalia** [decentraland/marketplace#763]
- [ ] Base

![image.png](https://images.zenhubusercontent.com/5ea09af31c23030cb8e249b8/ebbc1fa5-8f2a-4ba2-b838-f8c730b6b887)

Similar to the list for rent modal, the user has to input price per day, periods and expiration.

This data will come autofilled with the running listing.

The close button closes the modal.

The update listing will prompt the wallet to send a transaction to cancel the ongoing listing, after the transaction finishes a new wallet prompt appear to sign the new listing.

Once the new listing is signed, the data is sent to the backend and the modal is closed, showing the land detail page with the updated listing.

The remove listing will open the remove listing confirmation modal.

- [ ] Remove listing confirmation

![image.png](https://images.zenhubusercontent.com/5ea09af31c23030cb8e249b8/5671ad02-a0c4-486c-a8b9-0f4ae901a4e6)

Clicking on remove listing will send the cancellation transaction.

Once its done, close the modal and show a toast

- [ ] Cancelation toast

![image.png](https://images.zenhubusercontent.com/5ea09af31c23030cb8e249b8/b5aca14d-8ee2-4896-b784-8216b981c99c)

**Comment by LautaroPetaccio** [comment]
Closed issue in favor of #832
