### ISSUE TITLE
Rent modal

### ISSUE THREAD

**Issue by fzavalia** [decentraland/marketplace#765]
- [ ] First View

![image.png](https://images.zenhubusercontent.com/5ea09af31c23030cb8e249b8/597bc5b6-0729-4367-8e93-4610e973d764)

This view only shows if the mana contract has not received authorization yet.

Cancel closes the modal.

Allow will send the transaction to authorize.

Once the authorization is confirmed, show the second view

- [ ] Second View

![image.png](https://images.zenhubusercontent.com/5ea09af31c23030cb8e249b8/d0a69919-f374-4f59-ab57-ff2551c6c245)

The user has to input the amount of MANA that has to be paid as a confirmation mechanism.

The user can optionally input an operator. 

By checking the I will be operator box, the address of the user will be selected.

Once all fields are completed, the confirm button is enabled.

Clicking on cancel closes the modal.

Clicking on confirm will send the acceptListing transaction with the listing data and signature.

- [ ] Third view

![image.png](https://images.zenhubusercontent.com/5ea09af31c23030cb8e249b8/2967444f-acf6-4848-bad1-f53d43c99b88)

This shows when the transaction is confirmed.

**Comment by LautaroPetaccio** [comment]
Closing this issue in favor of #779 #780 and #781
