### ISSUE TITLE
Add rentals to LAND/Estate transaction history

### ISSUE THREAD

**Issue by fzavalia** [decentraland/marketplace#767]
![image.png](https://images.zenhubusercontent.com/5ea09af31c23030cb8e249b8/daae7e9f-3446-4fd6-a1c4-d86e8c7e9cd7)

**Comment by LautaroPetaccio** [comment]
Check what it the best solution:
- Modify the current subgraph to listen to the rental contract
- Split the latest sales table into two, "Latests sales" and "Latest rents"
