### ISSUE TITLE
Update the buy/mint UI to make prices clearer

### ISSUE THREAD

**Issue by nicosantangelo** [decentraland/marketplace#774]
## 🎉 Description

We should update both the BuyNFTModal and MintItemModal pages so the look like this:
https://www.figma.com/file/xT8BX45M2mRrp2oHZ0r9BW/Marketplace-New-Homepage?node-id=2449%3A11697

The error states (not enough MANA) for example, should be left as is

* [ ] 🐛 This is a bug report.
* [x] 📈 This is a feature request.

**Comment by LautaroPetaccio** [comment]
Closing it as it's this component is deprecated.
