### ISSUE TITLE
Can't find information for Estates sold

### ISSUE THREAD

**Issue by Sm00g15** [decentraland/marketplace#805]
## 🎉 Description

I'm trying to find information on Estates that have sold getting emitted from the blockchain. I asked a similar question in #663 , however I'm still not able to query assets to find out more about a sold estate. 

* [x ] This is a request for help.
* [ ] 🐛 This is a bug report.
* [ ] 📈 This is a feature request.

## 📝 Details

A) How can I tell if a property that has been sold is an estate or parcel? Are estates the one strictly with the assetId's with lengths usually under 5 or so? (ie: '559' or '1274')
B) From there how can I find out more data about these sales/estates? 

When referencing a clearly legit estate that's on sale: 
![screen shot 2019-01-06 at 3 58 20 pm](https://user-images.githubusercontent.com/14209806/50731538-5f37be00-11cc-11e9-8b23-e754f0340a4d.jpg)

I get nothing in response: 
![screen shot 2019-01-06 at 3 58 00 pm](https://user-images.githubusercontent.com/14209806/50731536-5a730a00-11cc-11e9-8789-8992df5b3286.jpg)

So, how can I go about accomplishing this?

**Comment by nachomazzara** [comment]
About point A. Could you provide more context?

About point B. Check my last comment here https://github.com/decentraland/marketplace/issues/663#issuecomment-451916940

**Comment by Sm00g15** [comment]
In regard to point A I got it. If the assetId is in integer format then it's an estate, whereas if the assetId is in BigNumber format it's a parcel.

Also I checked out your comment on Point B and that helped tremendously, thank you @nachomazzara

**Comment by Sm00g15** [comment]
@nachomazzara those both worked! thank you!

One final question: If I'm looking backward in the contracts how can I get sold estate data? I'm using:
`marketContract.getPastEvents(from, to etc etc) `

When using orderByAssetId I can get the created Estate orders , however when use auctionByAssetId I can't get the sold Estate data. 

![screen shot 2019-01-08 at 10 58 08 am](https://user-images.githubusercontent.com/14209806/50795813-55c96580-1334-11e9-8a8e-557dfb1af9bb.jpg)

**Comment by nachomazzara** [comment]
The order is deleted once it is executed. You should match the create event with the executed order event to get the info.

**Comment by Sm00g15** [comment]
fair enough, thank you for all your help @nachomazzara

**Comment by nachomazzara** [comment]
Yes, you can get the past `OrderSuccessful` event for the marketplace contract.

**Comment by Sm00g15** [comment]
ahh yes based on the assetId outcome... *facepalm* thanks Nacho
