### ISSUE TITLE
Some Publications not appearing in API

### ISSUE THREAD

**Issue by Hpauric** [decentraland/marketplace#905]
## 🎉 Description

Some marketplace transactions are not appearing in the marketplace api as publications.

* [x] 🐛 This is a bug report.
* [ ] 📈 This is a feature request.

## 📝 Details

For example, the following transaction was sent to the Marketplace contract:

https://etherscan.io/tx/0x9a0efded4975e975743c3135436240db54982e7a33a79c26e814e804471e9023

But it does not appear as a publication when queried in the Decentraland api:

https://api.decentraland.org/v1/publications/0x9a0efded4975e975743c3135436240db54982e7a33a79c26e814e804471e9023

## 👍 Other Information

When I query the transaction in web3, it seems fine:

```javascript
{ type: 'OrderCreated',
  assetId: '-93, -58',
  seller: '0x45A1089F3601e33bCef7ecC768AF68a65b15C09c',
  expiresAt: '1556316000000',
  priceInWei: '21500',
  block_number: 7463043,
  tx_id: '0x9a0efded4975e975743c3135436240db54982e7a33a79c26e814e804471e9023' }
```

**Comment by nachomazzara** [comment]
Hey!

If you create an order for an asset which has an active (open) order, the _old_ order will be deleted and replaced by the new one. The Marketplace contract only supports one active order per asset, therefore we do the same in our DB.

In your case the last order is: 
https://etherscan.io/tx/0xa95ea8e8803bce723a9cad99b5099f08d75e30aabb96858d8b0697406a8c434a

https://api.decentraland.org/v1/publications/0xa95ea8e8803bce723a9cad99b5099f08d75e30aabb96858d8b0697406a8c434a

**Comment by Hpauric** [comment]
Ah, I see. Makes sense, thanks! :grin:
