### ISSUE TITLE
[BUG] Button Rent keeps enabled after accepting a Rental Listing

### ISSUE THREAD

**Issue by juanmahidalgo** [decentraland/marketplace#921]
## 🎉 Description

As the title describes, once a Land/Estate is rented, the button keeps saying "Rent". If the Rent is executed, it shouldn't be shown as available. 

* [X] 🐛 This is a bug report.
* [ ] 📈 This is a feature request.

**Comment by LautaroPetaccio** [comment]
Probably related to #923
