### ISSUE TITLE
-86,-85 sold publication not appearing in decentraland api call

### ISSUE THREAD

**Issue by Hpauric** [decentraland/marketplace#922]
## 🎉 Description

The publication for the sale of parcel **-86,-85** yesterday (10th May 2019) is not appearing in the decentraland api

The tx hash is: **0xbbbc93f7aa9c73f5250dfb5f3e8c12a3672526d8fadf48e8101796ac58f8214f**

You can see it on etherscan:
https://etherscan.io/tx/0xbbbc93f7aa9c73f5250dfb5f3e8c12a3672526d8fadf48e8101796ac58f8214f

However a call for it in the decentraland api returns an error:

https://api.decentraland.org/v1/publications/0xbbbc93f7aa9c73f5250dfb5f3e8c12a3672526d8fadf48e8101796ac58f8214f

```javascript
{"ok":false,"data":{},"error":"Could not find a valid publication for the hash \"0xbbbc93f7aa9c73f5250dfb5f3e8c12a3672526d8fadf48e8101796ac58f8214f\""}
```

* [x] 🐛 This is a bug report.

**Comment by nachomazzara** [comment]
Hey, how are you? 

You need to use the order creation transaction hash instead.

It should be https://api.decentraland.org/v1/publications/0xb0022248bfea5546eb5cb9358ae8f8ec8ae54de16db421c40649d11b3c72daa0

https://etherscan.io/tx/0xb0022248bfea5546eb5cb9358ae8f8ec8ae54de16db421c40649d11b3c72daa0

Thanks!

**Comment by Hpauric** [comment]
Hey, thanks for clarifying! 😎
